run:
	env LOGCAT=service,session,op go run ./...

lint:
	go vet ./...

superlint:
	-go vet ./...
	-go vet -vettool=/Users/mike/go/bin/shadow ./...
	-staticcheck ./...
	-errcheck ./...
	-ineffassign ./...
	-deadcode

