bin/folio-list-users: bin/folio-list-users.go  service.go session.go http-error.go
	cd bin; go build -o folio-list-users ./...

run: bin/folio-list-users
	env LOGCAT=service,session,auth,op,curl,status,response bin/folio-list-users

lint:
	-go vet ./...
	-go vet -vettool=/Users/mike/go/bin/shadow ./...
	-staticcheck ./...
	-errcheck ./...
	-ineffassign ./...
	-deadcode

clean:
	rm -f bin/folio-list-users
