bin/folio-list-users:
	cd bin; go build -o folio-list-users ./...

run: bin/folio-list-users
	env LOGCAT=service,session,op,auth bin/folio-list-users

lint:
	go vet ./...

superlint:
	-go vet ./...
	-go vet -vettool=/Users/mike/go/bin/shadow ./...
	-staticcheck ./...
	-errcheck ./...
	-ineffassign ./...
	-deadcode

clean:
	rm -f bin/folio-list-users
